spring:
   application:
      name: shopping-cart-service
   datasource:
      url: jdbc:mysql://localhost:3306/shopping-cart-db
      username: root
      password: admin
   jpa:
      hibernate:
         ddl-auto: update
   properties:
      hibetnate:
         dialect: org.hibernate.dialect.MySQL5Dialect
      
server:
   port: 8085
   
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka
