server:
   port: 8081
spring:
   application:
      name: calatog-service
   datasource:
      url: jdbc:mysql://localhost:3306/catalog-db
      username: root
      password: admin
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect