server:
   port: 8083
spring:
   application:
      name: order-service
   datasource:
      url: jdbc:mysql://localhost:3306/order-db
      username: root
      password: admin
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect